/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author dc
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        
        setTanggal();
        jam();
    }
public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
    tglTF.setText(kal.format(skrg));
    }
public void jam() {
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SimpleDateFormat tgl = new SimpleDateFormat("EEEE-dd-MMM-yyyy");
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if (nilai_jam <= 9) {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9) {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9) {
                    nol_detik = "0";
                }
                String Jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jamTF.setText("  " + Jam + " : " + menit + " : " + detik + "  ");
                
            }
        };
        new javax.swing.Timer(1000, taskPerformer).start();
    }
     public void hakAksesPemilik(){
        
    }
    
    public void hakAksesKasir(){
        barangBT.setEnabled(false);
        xbarang.setEnabled(false);
        xpenjualan.setEnabled(false);
        xpengguna.setEnabled(false);
        xlappembelian.setEnabled(false);
        barangx.setEnabled(false);
        pembelianBT.setEnabled(false);
        supplierBT.setEnabled(false);
         homeBT.setEnabled(false);
    }
    
    public void hakAksesPersediaan(){
        xpengguna.setEnabled(false);
        xpenjualan.setEnabled(false);
        penjualanx.setEnabled(false);
        penjualanBT.setEnabled(false);
        homeBT.setEnabled(false);
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        supplierBT = new javax.swing.JButton();
        pembelianBT = new javax.swing.JButton();
        penjualanBT = new javax.swing.JButton();
        homeBT = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        barangBT = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jam = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jamTF = new javax.swing.JLabel();
        tglTF = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dp = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        xbarang = new javax.swing.JMenu();
        masterx = new javax.swing.JMenuItem();
        xsupplier = new javax.swing.JMenuItem();
        xpenjualan = new javax.swing.JMenu();
        xtrans = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        barangx = new javax.swing.JMenuItem();
        xlappembelian = new javax.swing.JMenuItem();
        penjualanx = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        xpengguna = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 750));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CV ANUGERAH SEJETERAH");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ALAT.jpg"))); // NOI18N
        jLabel4.setText("JL LEBAK SARI TANJUNG BARAT NO 3 JAKARTA SELATAN");

        supplierBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supplierBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Suplier.png"))); // NOI18N
        supplierBT.setText("DATA SUPPLIER");
        supplierBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBTActionPerformed(evt);
            }
        });

        pembelianBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pembelianBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pembelian.png"))); // NOI18N
        pembelianBT.setText("PEMBELIAN BARANG");
        pembelianBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianBTActionPerformed(evt);
            }
        });

        penjualanBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        penjualanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penjualan.png"))); // NOI18N
        penjualanBT.setText("PENJUALAN BARANG");
        penjualanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanBTActionPerformed(evt);
            }
        });

        homeBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home-icon.png"))); // NOI18N
        homeBT.setText("HOME");
        homeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-help-32.png"))); // NOI18N
        jButton6.setText("HELP");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("JL LEBAK SARI NO.23 JAKARTA SELATAN");

        barangBT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        barangBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/barang1.png"))); // NOI18N
        barangBT.setText("DATA BARANG");
        barangBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(551, 551, 551))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(homeBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(barangBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supplierBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pembelianBT, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                                    .addComponent(penjualanBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jSeparator11))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(homeBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barangBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierBT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembelianBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penjualanBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 750));

        jam.setBackground(new java.awt.Color(204, 204, 255));
        jam.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));
        jam.setPreferredSize(new java.awt.Dimension(1500, 130));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("APLIKASI PENJUALAN ALAT KESEHATAN");

        jamTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jamTF.setText("JAM");

        tglTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tglTF.setText("TANGGAL");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jamLayout = new javax.swing.GroupLayout(jam);
        jam.setLayout(jamLayout);
        jamLayout.setHorizontalGroup(
            jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jamTF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tglTF, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(102, 102, 102))
        );
        jamLayout.setVerticalGroup(
            jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jamLayout.createSequentialGroup()
                .addGroup(jamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jamLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jamTF, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tglTF)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 1090, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/alat2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        dp.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 1080, 620));

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        xbarang.setText("master");

        masterx.setText("barang");
        masterx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterxActionPerformed(evt);
            }
        });
        xbarang.add(masterx);

        xsupplier.setText("supplier");
        xsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsupplierActionPerformed(evt);
            }
        });
        xbarang.add(xsupplier);

        jMenuBar1.add(xbarang);

        xpenjualan.setText("transaksi");

        xtrans.setText("Pembeliaan");
        xtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtransActionPerformed(evt);
            }
        });
        xpenjualan.add(xtrans);

        jMenuItem3.setText("Penjualan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        xpenjualan.add(jMenuItem3);

        jMenuBar1.add(xpenjualan);

        jMenu2.setText("laporan");

        barangx.setText("barang");
        barangx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangxActionPerformed(evt);
            }
        });
        jMenu2.add(barangx);

        xlappembelian.setText("pembelian");
        xlappembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlappembelianActionPerformed(evt);
            }
        });
        jMenu2.add(xlappembelian);

        penjualanx.setText("penjualan");
        penjualanx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanxActionPerformed(evt);
            }
        });
        jMenu2.add(penjualanx);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Utility");

        xpengguna.setText("datapengguna");
        xpengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpenggunaActionPerformed(evt);
            }
        });
        jMenu5.add(xpengguna);

        jMenuItem8.setText("gantipassword");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("help");

        jMenuItem9.setText("tentang aplikasi");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem2.setText("help");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barangBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBTActionPerformed
        // TODO add your handling code here:
         barang b= new barang();
       dp.add(b);
       adm a = new adm();
       dp.remove(a);
        b.setVisible(true);
    }//GEN-LAST:event_barangBTActionPerformed

    private void supplierBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBTActionPerformed
        // TODO add your handling code here:
        supplier sp= new supplier();
       dp.add(sp);
       adm a = new adm();
       dp.remove(a);
        sp.setVisible(true);
    }//GEN-LAST:event_supplierBTActionPerformed

    private void pembelianBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianBTActionPerformed
        // TODO add your handling code here:
        bbarang bb= new bbarang();
       dp.add(bb);
       adm a = new adm();
       dp.remove(a);
        bb.setVisible(true);
    }//GEN-LAST:event_pembelianBTActionPerformed

    private void penjualanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanBTActionPerformed
        // TODO add your handling code here:
        jual j= new jual();
       dp.add(j);
       adm a = new adm();
       dp.remove(a);
        j.setVisible(true);
    }//GEN-LAST:event_penjualanBTActionPerformed

    private void masterxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterxActionPerformed
        // TODO add your handling code here:
         barang b= new barang();
       dp.add(b);
       adm a = new adm();
       dp.remove(a);
        b.setVisible(true);
    }//GEN-LAST:event_masterxActionPerformed

    private void xtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtransActionPerformed
        // TODO add your handling code here:
          bbarang bb= new bbarang();
       dp.add(bb);
       adm a = new adm();
       dp.remove(a);
        bb.setVisible(true);
    }//GEN-LAST:event_xtransActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         jual j= new jual();
       dp.add(j);
       adm a = new adm();
       dp.remove(a);
        j.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void xlappembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlappembelianActionPerformed
        // TODO add your handling code here:
         laporanpembelian lp=new laporanpembelian();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
      
         
    
    }//GEN-LAST:event_xlappembelianActionPerformed

    private void penjualanxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanxActionPerformed
        // TODO add your handling code here:
         laporanpenjualan lp=new laporanpenjualan();
        lp.setLocationRelativeTo(null);
        lp.setVisible(true);
      
     
    }//GEN-LAST:event_penjualanxActionPerformed

    private void barangxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangxActionPerformed
        // TODO add your handling code here
         laporanbarang lb=new laporanbarang();
        lb.setLocationRelativeTo(null);
        lb.setVisible(true);
      
         
    
    }//GEN-LAST:event_barangxActionPerformed

    private void xpenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpenggunaActionPerformed
        // TODO add your handling code here:
         daftar d=new daftar();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
      
        
    }//GEN-LAST:event_xpenggunaActionPerformed

    private void xsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsupplierActionPerformed
        // TODO add your handling code here:
           supplier sp= new supplier();
       dp.add(sp);
       adm a = new adm();
       dp.remove(a);
        sp.setVisible(true);
    }//GEN-LAST:event_xsupplierActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
         help h=new help();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         help h=new help();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
        

        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         about a=new about();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         help h=new help();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void homeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTActionPerformed
        // TODO add your handling code here:
         menu a = new menu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeBTActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        gantipassword h=new gantipassword();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        login h=new login();
        h.setLocationRelativeTo(null);
        h.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangBT;
    private javax.swing.JMenuItem barangx;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JButton homeBT;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel jam;
    private javax.swing.JLabel jamTF;
    private javax.swing.JMenuItem masterx;
    private javax.swing.JButton pembelianBT;
    private javax.swing.JButton penjualanBT;
    private javax.swing.JMenuItem penjualanx;
    private javax.swing.JButton supplierBT;
    private javax.swing.JLabel tglTF;
    private javax.swing.JMenu xbarang;
    private javax.swing.JMenuItem xlappembelian;
    private javax.swing.JMenuItem xpengguna;
    private javax.swing.JMenu xpenjualan;
    private javax.swing.JMenuItem xsupplier;
    private javax.swing.JMenuItem xtrans;
    // End of variables declaration//GEN-END:variables

}
